[package]
name = "fftw"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

description = "safe wrapper of FFTW3"
repository = "https://github.com/termoshtt/rust-fftw3"
keywords = ["fftw"]
license = "GPL-3.0"

[features]
default = ["source"]
system = ["fftw-sys/system"]
source = ["fftw-sys/source"]

[dependencies]
num-traits  = { git = "http://github.com/rust-num/num" }
num-complex = { git = "http://github.com/rust-num/num" }
lazy_static = "0.2.2"

[dependencies.fftw-sys]
path = "fftw-sys"
default-features = false

[dev-dependencies]
float-cmp = "0.2.3"
